# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

project_name: prusalink-go

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    binary: prusalink
    main: ./cli
    goos: [linux, windows, darwin]
    goarch: [amd64, arm64]
    ldflags:
      - -X github.com/ysmilda/prusalink-go/cli/cli.version={{.Version}}
      - -X github.com/ysmilda/prusalink-go/cli/cli.commit={{.Commit}}
      - -X github.com/ysmilda/prusalink-go/cli/cli.date={{.Date}}

dockers:
  - goos: linux
    goarch: amd64
    dockerfile: .goreleaser.dockerfile
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/ysmilda/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/ysmilda/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
    image_templates:
      - "ghcr.io/ysmilda/{{ .ProjectName }}:v{{ .Major }}-amd64"
      - "ghcr.io/ysmilda/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/ysmilda/{{ .ProjectName }}:latest-amd64"

  - goos: linux
    goarch: arm64
    dockerfile: .goreleaser.dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64/v8"
    image_templates:
      - "ghcr.io/ysmilda/{{ .ProjectName }}:v{{ .Major }}-arm64v8"
      - "ghcr.io/ysmilda/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-arm64v8"
      - "ghcr.io/ysmilda/{{ .ProjectName }}:latest-arm64v8"

docker_manifests:
  - name_template: "ghcr.io/ysmilda/{{ .ProjectName }}:v{{.Major}}"
    image_templates:
      - "ghcr.io/ysmilda/{{ .ProjectName }}:v{{ .Major }}-amd64"
      - "ghcr.io/ysmilda/{{ .ProjectName }}:v{{ .Major }}-arm64v8"

  - name_template: "ghcr.io/ysmilda/{{ .ProjectName }}:v{{.Major}}.{{ .Minor }}"
    image_templates:
      - "ghcr.io/ysmilda/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/ysmilda/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-arm64v8"

  - name_template: "ghcr.io/ysmilda/{{ .ProjectName }}:latest"
    image_templates:
      - "ghcr.io/ysmilda/{{ .ProjectName }}:latest-amd64"
      - "ghcr.io/ysmilda/{{ .ProjectName }}:latest-arm64v8"

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
